# Link this file to ~/.config/ghostty/config.

# Set specific theme, list all themes use: ghostty +list-themes.
theme = GitHub Dark Default
# Set term type to avoid some incompatible.
term = xterm-256color
# Keyboard for quick terminal.
keybind = global:cmd+shift+enter=toggle_quick_terminal

# Cursor configs.
cursor-style = block
shell-integration = fish
shell-integration-features = no-cursor

# Font configs.
font-family = CascadiaCodeNF-Regular
font-size = 12

# Window configs.
window-height = 40
window-width = 120
window-padding-x = 10
window-padding-y = 10

# Background configs.
background-opacity = 0.8
background-blur = true
